### ISSUE TITLE
Only 3GB Ram on BPI-R4

### ISSUE THREAD

**Issue by HeyMeco** [frank-w/BPI-Router-Images#10]
I built a bookworm image with kernel set to `6.10` and for some reason theres only 3GB of RAM showing up.
`/boot/uEnv.txt` is empty and writing `mem=4GB` also didn't change anything. Am I missing something?

**Comment by frank-w** [comment]
Is it printed in linux cmdline? It is possible that i have not removed it from builtin env in uboot

**Comment by frank-w** [comment]
Yes it is still there

https://github.com/frank-w/u-boot/blob/2024-04-bpi/uEnv_r4.txt#L18

You can overrid it with your uEnv.txt by setting bootopts again

**Comment by HeyMeco** [comment]
@frank-w 
> You can overrid it with your uEnv.txt by setting bootopts again

Yup apparently I was missing the `bootopts=` when adding `mem=4GB` now all 4GB are being recognized. 
Thanks for the amazing work and help!

**Comment by frank-w** [comment]
You can just override this setting by empty value or only the debug=7

No need to say tell the right size...we had only limit to 3g as network driver and the ppe had issues with 4g
