### ISSUE TITLE
Banana_Pi_BPI-R3 Mini Support

### ISSUE THREAD

**Issue by tfcarlin** [frank-w/BPI-Router-Images#4]
Any idea if this will work with the Mini version? I have one but not sure how to proceed to install to test (which I'm happy to do with some guidance).

**Comment by frank-w** [comment]
No,only normal r3 is supported. I do not have r3 mini and afaik it has no sdcard slot...i'm unsure how to flash it correctly..maybe flash emmc image after booting from nand. But then a emmc image has to be created... currently only sdcard base image is build in my uboot repo

**Comment by tfcarlin** [comment]
Thanks for the update.
