### ISSUE TITLE
can't boot bpi-r4

### ISSUE THREAD

**Issue by ChrisSiedler** [frank-w/BPI-Router-Images#7]
Dear Frank, 
thanks for your great work.

I have a bpi-r4, tried to create a debian 12 image with your tools.

`./buildimg.sh bpi-r4 bookworm`

It build the image without problems, I copied it to the sd card, changed the jumpers to sd card.

Then, when I tried to boot the bpi-r4, I saw the following message:

```
## Error: "initrd" not defined
PARTITION_CONFIG only exists on eMMC
sd available
bootconf=#conf-sd
fit=bpi-r4.itb
Failed to load 'bpi-r4.itb'
BPI-R4> 
```

Any help is appreciated

**Comment by frank-w** [comment]
first 2 can be ignored.

first one is check for initrd variable (printenv command shows error buti only check return value - so not using initrd if undefined)

second one is check for emmc, if this failes use the sd config which is done

your main problem is that it seems to be no bpi-r4.itb on BPI-Boot-Partition on sdcard

**Comment by ChrisSiedler** [comment]
can confirm, with `kernel="6.9"` the script is creating a good image.
The bpi-r4 is booting now.

Thanks for the amazing quick support!
